# Generated by Django 5.0.6 on 2024-09-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
